# Generated by Django 4.2.1 on 2023-05-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sort_order']},
        ),
    ]
